project 'JordanHeadMeme.xcodeproj'

platform :ios, '8.0'
target 'JordanHeadMeme' do
  use_frameworks!
#  pod 'SVProgressHUD' until the beta can handle it, cant do nothing
  pod 'Fabric'
  pod 'Crashlytics'
#  pod 'TSMessages', :git => 'https://github.com/KrauseFx/TSMessages.git' until the beta can handle it, cant do nothing
end
